version: '3.4'

services:
  api:
    image: polyrific/opencatapult:1.0.0-beta2-api
    build:
      context: .
      dockerfile: src/API/Polyrific.Catapult.Api/Dockerfile
    depends_on:
      - mssqldb
  mssqldb:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    environment:
      - ACCEPT_EULA="Y"
